packages:
  - "apps/*"
onlyBuiltDependencies:
  - "@firebase/util"
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - protobufjs
  - sharp
  - unrs-resolver
patchedDependencies:
  next-themes@0.4.6: patches/next-themes@0.4.6.patch
