TASKS = "tasks"
PROJECTS = "projects"
BOOKMARKS = "bookmarks"
BOOKMARK_FOLDERS = "bookmarkFolders"
PASSWORD_VAULTS = "passwordVaults"
PASSWORD_ENTRIES = "passwordEntries"
NOTES = "notes"
NOSQL_CONNECTIONS = "mongodb_connections"