[package]
name = "mydevtools-desktop"
version = "0.1.14"
description = "MyDevTools desktop app"
edition = "2021"

[lib]
name = "mydevtools_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled-sqlcipher-vendored-openssl"] }
keyring = { version = "3", features = ["apple-native"] }
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
rand = "0.8"
thiserror = "2"
reqwest = { version = "0.12", features = ["json", "gzip", "multipart", "stream"] }
base64 = "0.22"
tauri-plugin-opener = "2"
tauri-plugin-window-state = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tokio = { version = "1", features = ["time", "sync", "net", "io-util"] }
tokio-postgres = "0.7"
postgres-native-tls = "0.5"
native-tls = { version = "0.2", features = ["alpn"] }
tokio-native-tls = "0.3"
h2 = "0.4"
http = "1"
bytes = "1"
mysql_async = { version = "0.36", default-features = false, features = ["default-rustls-ring"] }
mongodb = "3"
redis = { version = "1.6", features = ["tokio-comp", "tokio-native-tls-comp"] }
futures-util = "0.3"
dashmap = "6"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[profile.release]
strip = true
lto = true
