#!/usr/bin/env python3
"""Writes snippet-manager-patches.json for merge-snippet-manager-i18n.mjs (full SnippetManager UI)."""

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "snippet-manager-patches.json"
OUT_NAV_DASH = Path(__file__).resolve().parent / "snippet-manager-nav-dash-patches.json"

# Navigation.snippetManager + Dashboard.tools.snippetManager (card on dashboard)
NAV_DASH: dict[str, dict[str, str]] = {
    "fr": {
        "navigation": "Extraits de code",
        "title": "Extraits de code",
        "description": "Enregistrez des extraits avec coloration syntaxique, détection automatique du langage et formatage.",
    },
    "de": {
        "navigation": "Code-Snippets",
        "title": "Code-Snippets",
        "description": "Snippets mit Syntaxhervorhebung, automatischer Spracherkennung und Formatierung speichern.",
    },
    "es": {
        "navigation": "Fragmentos de código",
        "title": "Fragmentos de código",
        "description": "Guarda fragmentos con resaltado de sintaxis, detección automática de idioma y formato.",
    },
    "it": {
        "navigation": "Snippet di codice",
        "title": "Snippet di codice",
        "description": "Salva snippet con evidenziazione sintattica, rilevamento automatico della lingua e formattazione.",
    },
    "pt": {
        "navigation": "Excertos de código",
        "title": "Excertos de código",
        "description": "Guarde excertos com realce de sintaxe, deteção automática de linguagem e formatação.",
    },
    "pt-BR": {
        "navigation": "Trechos de código",
        "title": "Trechos de código",
        "description": "Salve trechos com realce de sintaxe, detecção automática de linguagem e formatação.",
    },
    "nl": {
        "navigation": "Codefragmenten",
        "title": "Codefragmenten",
        "description": "Bewaar fragmenten met syntaxisaccentuering, automatische taaldetectie en opmaak.",
    },
    "pl": {
        "navigation": "Fragmenty kodu",
        "title": "Fragmenty kodu",
        "description": "Zapisuj fragmenty z podświetlaniem składni, autowykrywaniem języka i formatowaniem.",
    },
    "ru": {
        "navigation": "Фрагменты кода",
        "title": "Фрагменты кода",
        "description": "Сохраняйте сниппеты с подсветкой синтаксиса, автоопределением языка и форматированием.",
    },
    "uk": {
        "navigation": "Фрагменти коду",
        "title": "Фрагменти коду",
        "description": "Зберігайте фрагменти з підсвічуванням синтаксису, авто-визначенням мови та форматуванням.",
    },
    "tr": {
        "navigation": "Kod parçacıkları",
        "title": "Kod parçacıkları",
        "description": "Sözdizimi vurgulama, otomatik dil algılama ve biçimlendirme ile parçacıkları kaydedin.",
    },
    "ar": {
        "navigation": "مقاطع الشيفرة",
        "title": "مقاطع الشيفرة",
        "description": "احفظ المقاطع مع تمييز بناء الجملة وكشف اللغة التلقائي والتنسيق.",
    },
    "fa": {
        "navigation": "قطعه‌کدها",
        "title": "قطعه‌کدها",
        "description": "قطعه‌کدها را با برجسته‌سازی نحو، تشخیص خودکار زبان و قالب‌بندی ذخیره کنید.",
    },
    "zh": {
        "navigation": "代码片段",
        "title": "代码片段",
        "description": "保存代码片段，支持语法高亮、自动检测语言和格式化。",
    },
    "ja": {
        "navigation": "コードスニペット",
        "title": "コードスニペット",
        "description": "シンタックスハイライト、自動言語検出、整形でスニペットを保存します。",
    },
    "ko": {
        "navigation": "코드 스니펫",
        "title": "코드 스니펫",
        "description": "구문 강조, 자동 언어 감지 및 서식으로 스니펫을 저장하세요.",
    },
    "vi": {
        "navigation": "Đoạn mã",
        "title": "Đoạn mã",
        "description": "Lưu đoạn mã với tô sáng cú pháp, tự động nhận diện ngôn ngữ và định dạng.",
    },
    "id": {
        "navigation": "Cuplikan kode",
        "title": "Cuplikan kode",
        "description": "Simpan cuplikan dengan penyorotan sintaks, deteksi bahasa otomatis, dan pemformatan.",
    },
    "ms": {
        "navigation": "Petikan kod",
        "title": "Petikan kod",
        "description": "Simpan petikan dengan sorotan sintaks, pengesanan bahasa automatik dan pemformatan.",
    },
    "cs": {
        "navigation": "Úryvky kódu",
        "title": "Úryvky kódu",
        "description": "Ukládejte úryvky se zvýrazněním syntaxe, automatickou detekcí jazyka a formátováním.",
    },
    "el": {
        "navigation": "Αποσπάσματα κώδικα",
        "title": "Αποσπάσματα κώδικα",
        "description": "Αποθηκεύστε αποσπάσματα με τονισμό σύνταξης, αυτόματη ανίχνευση γλώσσας και μορφοποίηση.",
    },
    "da": {
        "navigation": "Kodestykker",
        "title": "Kodestykker",
        "description": "Gem kodestykker med syntaksfremhævelse, automatisk sprogdetektion og formatering.",
    },
    "nb": {
        "navigation": "Kodeutdrag",
        "title": "Kodeutdrag",
        "description": "Lagre utdrag med syntaksutheving, automatisk språkgjenkjenning og formatering.",
    },
    "sv": {
        "navigation": "Kodutdrag",
        "title": "Kodutdrag",
        "description": "Spara utdrag med syntaxmarkering, automatisk språkupptäckt och formatering.",
    },
    "af": {
        "navigation": "Kodesnippette",
        "title": "Kodesnippette",
        "description": "Bewaar snippette met sintaks-beklemtoning, outomatiese taalopsporing en formatering.",
    },
    "ca": {
        "navigation": "Fragments de codi",
        "title": "Fragments de codi",
        "description": "Desa fragments amb ressaltat de sintaxi, detecció automàtica d’idioma i format.",
    },
}

# Programming-language ids stay English; only translate user-facing UI.
LANG = {
    "en": ("Auto-detect", "Plain text"),
    "fr": ("Détection automatique", "Texte brut"),
    "es": ("Detección automática", "Texto sin formato"),
    "de": ("Automatisch erkennen", "Nur Text"),
    "it": ("Rilevamento automatico", "Testo normale"),
    "pt": ("Deteção automática", "Texto simples"),
    "pt-BR": ("Detecção automática", "Texto simples"),
    "nl": ("Automatisch detecteren", "Platte tekst"),
    "pl": ("Wykrywanie automatyczne", "Zwykły tekst"),
    "ru": ("Автоопределение", "Простой текст"),
    "uk": ("Автовизначення", "Звичайний текст"),
    "tr": ("Otomatik algıla", "Düz metin"),
    "ar": ("اكتشاف تلقائي", "نص عادي"),
    "fa": ("تشخیص خودکار", "متن ساده"),
    "zh": ("自动检测", "纯文本"),
    "ja": ("自動検出", "プレーンテキスト"),
    "ko": ("자동 감지", "일반 텍스트"),
    "vi": ("Tự động nhận diện", "Văn bản thuần"),
    "id": ("Deteksi otomatis", "Teks biasa"),
    "ms": ("Auto kesan", "Teks biasa"),
    "cs": ("Automatická detekce", "Prostý text"),
    "el": ("Αυτόματη ανίχνευση", "Απλό κείμενο"),
    "da": ("Automatisk registrering", "Almindelig tekst"),
    "nb": ("Automatisk gjenkjenning", "Ren tekst"),
    "sv": ("Automatisk avkänning", "Oformaterad text"),
    "af": ("Outomatiese opsporing", "Gewone teks"),
    "ca": ("Detecció automàtica", "Text sense format"),
}


def code_sample(l1: str, l2: str) -> str:
    return (
        f"{l1}\n{l2}\n"
        "function greet(name) {\n"
        "  return `Hello, ${name}!`;\n"
        "}"
    )


def pack(
    loc: str,
    *,
    title: str,
    snippets: str,
    new_snippet: str,
    new_title: str,
    welcome: str,
    c1: str,
    c2: str,
    search_ph: str,
    search_ar: str,
    empty: str,
    st: str,
    st_ph: str,
    lang: str,
    det: str,
    badge: str,
    view: str,
    edit: str,
    copy: str,
    copied: str,
    fmt: str,
    cancel: str,
    del_t: str,
    del_d: str,
    del_ok: str,
    ed_ar: str,
    ed_ld: str,
    tc: str,
    tcf: str,
    tnt: str,
    tfm: str,
    tff: str,
    tfj: str,
    tfu: str,
    tdel: str,
    tlf: str,
    tsf: str,
    sub: str,
) -> dict:
    auto, plain = LANG[loc]
    return {
        "title": title,
        "subtitle": sub,
        "snippets": snippets,
        "newSnippet": new_snippet,
        "newSnippetTitle": new_title,
        "defaultSnippetTitle": welcome,
        "defaultSnippetCode": code_sample(c1, c2),
        "searchPlaceholder": search_ph,
        "searchAria": search_ar,
        "emptySearch": empty,
        "snippetTitle": st,
        "snippetTitlePlaceholder": st_ph,
        "language": lang,
        "detectedHint": det,
        "badgeAuto": badge,
        "modeView": view,
        "modeEdit": edit,
        "copy": copy,
        "copied": copied,
        "format": fmt,
        "cancel": cancel,
        "deleteTitle": del_t,
        "deleteDescription": del_d,
        "deleteConfirm": del_ok,
        "editorAria": ed_ar,
        "editorLoading": ed_ld,
        "toastCopied": tc,
        "toastCopyFailed": tcf,
        "toastNothingToCopy": tnt,
        "toastFormatted": tfm,
        "toastFormatFailed": tff,
        "toastFormatJsonInvalid": tfj,
        "toastFormatUnsupported": tfu,
        "toastDeleted": tdel,
        "toastLoadFailed": tlf,
        "toastSyncFailed": tsf,
        "languages": {"auto": auto, "plaintext": plain},
    }


# Subtitles / server toasts / dashboard label — keep aligned with apply-snippet-dashboard-i18n.py
SUB = {
    "fr": (
        "Enregistrez des extraits dans votre navigateur ou connectez-vous pour les synchroniser avec votre compte. Passez de la consultation à l’édition, copiez en un clic, choisissez un langage ou la détection automatique, et formatez JSON, SQL ou le code pris en charge par Monaco.",
        "Impossible de charger les extraits depuis le serveur.",
        "Impossible de synchroniser avec le serveur.",
    ),
    "de": (
        "Speichern Sie Snippets im Browser oder melden Sie sich an, um sie mit Ihrem Konto zu synchronisieren. Wechseln Sie zwischen Ansicht und Bearbeitung, kopieren Sie mit einem Klick, wählen Sie eine Sprache oder Auto-Erkennung und formatieren Sie JSON, SQL oder von Monaco unterstützten Code.",
        "Snippets konnten nicht vom Server geladen werden.",
        "Synchronisation mit dem Server fehlgeschlagen.",
    ),
    "es": (
        "Guarda fragmentos en tu navegador o inicia sesión para sincronizarlos con tu cuenta. Cambia entre ver y editar, copia con un clic, elige idioma o detección automática y formatea JSON, SQL o código compatible con Monaco.",
        "No se pudieron cargar los fragmentos desde el servidor.",
        "No se pudo sincronizar con el servidor.",
    ),
    "it": (
        "Conserva gli snippet nel browser o accedi per sincronizzarli con il tuo account. Passa da visualizzazione a modifica, copia con un clic, scegli la lingua o il rilevamento automatico e formatta JSON, SQL o codice supportato da Monaco.",
        "Impossibile caricare gli snippet dal server.",
        "Impossibile sincronizzare con il server.",
    ),
    "pt": (
        "Guarde excertos no navegador ou inicie sessão para os sincronizar com a sua conta. Alterne entre ver e editar, copie com um clique, escolha a linguagem ou deteção automática e formate JSON, SQL ou código suportado pelo Monaco.",
        "Não foi possível carregar os excertos do servidor.",
        "Não foi possível sincronizar com o servidor.",
    ),
    "pt-BR": (
        "Armazene trechos no navegador ou entre para sincronizá-los com sua conta. Alterne entre ver e editar, copie com um clique, escolha a linguagem ou detecção automática e formate JSON, SQL ou código suportado pelo Monaco.",
        "Não foi possível carregar os trechos do servidor.",
        "Não foi possível sincronizar com o servidor.",
    ),
    "nl": (
        "Bewaar snippets in je browser of log in om ze met je account te synchroniseren. Wissel tussen bekijken en bewerken, kopieer met één klik, kies een taal of automatische detectie en formatteer JSON, SQL of door Monaco ondersteunde code.",
        "Snippets konden niet van de server worden geladen.",
        "Synchroniseren met de server is mislukt.",
    ),
    "pl": (
        "Przechowuj fragmenty kodu w przeglądarce lub zaloguj się, aby synchronizować je z kontem. Przełączaj widok i edycję, kopiuj jednym kliknięciem, wybierz język lub autowykrywanie i formatuj JSON, SQL lub kod obsługiwany przez Monaco.",
        "Nie udało się wczytać fragmentów z serwera.",
        "Nie udało się zsynchronizować z serwerem.",
    ),
    "ru": (
        "Храните сниппеты в браузере или войдите, чтобы синхронизировать их с аккаунтом. Переключайтесь между просмотром и правкой, копируйте в один клик, выбирайте язык или автоопределение и форматируйте JSON, SQL или код, поддерживаемый Monaco.",
        "Не удалось загрузить сниппеты с сервера.",
        "Не удалось синхронизировать с сервером.",
    ),
    "uk": (
        "Зберігайте фрагменти коду в браузері або увійдіть, щоб синхронізувати їх з обліковим записом. Перемикайте перегляд і редагування, копіюйте одним кліком, обирайте мову або авто-визначення та форматуйте JSON, SQL або код, який підтримує Monaco.",
        "Не вдалося завантажити фрагменти з сервера.",
        "Не вдалося синхронізувати з сервером.",
    ),
    "tr": (
        "Parçacıkları tarayıcıda saklayın veya hesabınızla eşitlemek için oturum açın. Görüntüleme ve düzenleme arasında geçiş yapın, tek tıkla kopyalayın, dil seçin veya otomatik algılayın ve JSON, SQL veya Monaco destekli kodu biçimlendirin.",
        "Parçacıklar sunucudan yüklenemedi.",
        "Sunucu ile eşitleme başarısız oldu.",
    ),
    "ar": (
        "خزّن المقاطع في المتصفح أو سجّل الدخول لمزامنتها مع حسابك. بدّل بين العرض والتحرير، انسخ بنقرة واحدة، اختر لغة أو كشفًا تلقائيًا، ونسّق JSON أو SQL أو أكواد يدعمها Monaco.",
        "تعذّر تحميل المقاطع من الخادم.",
        "تعذّرت المزامنة مع الخادم.",
    ),
    "fa": (
        "قطعه‌کدها را در مرورگر نگه دارید یا برای همگام‌سازی با حساب وارد شوید. بین مشاهده و ویرایش جابه‌جا شوید، با یک کلیک کپی کنید، زبان را انتخاب یا خودکار تشخیص دهید و JSON، SQL یا کد پشتیبانی‌شده توسط Monaco را قالب‌بندی کنید.",
        "بارگیری قطعه‌کدها از سرور انجام نشد.",
        "همگام‌سازی با سرور انجام نشد.",
    ),
    "zh": (
        "在浏览器中保存代码片段，或登录以同步到账户。在查看与编辑间切换、一键复制、选择语言或使用自动检测，并格式化 JSON、SQL 或 Monaco 支持的代码。",
        "无法从服务器加载代码片段。",
        "无法与服务器同步。",
    ),
    "ja": (
        "ブラウザにスニペットを保存するか、サインインしてアカウントと同期します。表示と編集の切り替え、ワンクリックコピー、言語の選択または自動検出、JSON・SQL・Monaco 対応コードの整形ができます。",
        "サーバーからスニペットを読み込めませんでした。",
        "サーバーと同期できませんでした。",
    ),
    "ko": (
        "브라우저에 스니펫을 저장하거나 로그인해 계정과 동기화하세요. 보기와 편집 전환, 한 번의 클릭으로 복사, 언어 선택 또는 자동 감지, JSON·SQL·Monaco 지원 코드 포맷을 사용할 수 있습니다.",
        "서버에서 스니펫을 불러오지 못했습니다.",
        "서버와 동기화하지 못했습니다.",
    ),
    "vi": (
        "Lưu đoạn mã trong trình duyệt hoặc đăng nhập để đồng bộ với tài khoản. Chuyển giữa xem và sửa, sao chép một cú nhấp, chọn ngôn ngữ hoặc tự động nhận diện, và định dạng JSON, SQL hoặc mã được Monaco hỗ trợ.",
        "Không thể tải đoạn mã từ máy chủ.",
        "Không thể đồng bộ với máy chủ.",
    ),
    "id": (
        "Simpan cuplikan di browser atau masuk untuk menyinkronkannya dengan akun Anda. Beralih antara lihat dan sunting, salin sekali klik, pilih bahasa atau deteksi otomatis, dan format JSON, SQL, atau kode yang didukung Monaco.",
        "Tidak dapat memuat cuplikan dari server.",
        "Tidak dapat menyinkronkan dengan server.",
    ),
    "ms": (
        "Simpan petikan dalam pelayar atau log masuk untuk menyelaraskannya dengan akaun anda. Tukar antara lihat dan sunting, salin satu klik, pilih bahasa atau auto kesan, dan format JSON, SQL atau kod yang disokong Monaco.",
        "Tidak dapat memuatkan petikan dari pelayan.",
        "Tidak dapat menyelaraskan dengan pelayan.",
    ),
    "cs": (
        "Ukládejte úryvky v prohlížeči nebo se přihlaste a synchronizujte je s účtem. Přepínejte zobrazení a úpravy, kopírujte jedním kliknutím, volte jazyk nebo automatickou detekci a formátujte JSON, SQL nebo kód podporovaný Monacem.",
        "Úryvky se nepodařilo načíst ze serveru.",
        "Synchronizace se serverem se nezdařila.",
    ),
    "el": (
        "Αποθηκεύστε αποσπάσματα στον browser ή συνδεθείτε για συγχρονισμό με τον λογαριασμό σας. Εναλλαγή προβολής και επεξεργασίας, αντιγραφή με ένα κλικ, επιλογή γλώσσας ή αυτόματη ανίχνευση και μορφοποίηση JSON, SQL ή κώδικα που υποστηρίζει το Monaco.",
        "Δεν ήταν δυνατή η φόρτωση αποσπασμάτων από τον διακομιστή.",
        "Δεν ήταν δυνατός ο συγχρονισμός με τον διακομιστή.",
    ),
    "da": (
        "Gem snippets i browseren eller log ind for at synkronisere med din konto. Skift mellem visning og redigering, kopiér med ét klik, vælg sprog eller autodetektér, og formatér JSON, SQL eller Monaco-understøttet kode.",
        "Kunne ikke indlæse snippets fra serveren.",
        "Kunne ikke synkronisere med serveren.",
    ),
    "nb": (
        "Lagre utdrag i nettleseren eller logg inn for å synkronisere med kontoen din. Bytt mellom visning og redigering, kopier med ett klikk, velg språk eller automatisk gjenkjenning, og formater JSON, SQL eller Monaco-støttet kode.",
        "Kunne ikke laste utdrag fra serveren.",
        "Kunne ikke synkronisere med serveren.",
    ),
    "sv": (
        "Spara utdrag i webbläsaren eller logga in för att synka med ditt konto. Växla mellan visning och redigering, kopiera med ett klick, välj språk eller autoupptäckt, och formatera JSON, SQL eller Monaco-stödd kod.",
        "Kunde inte läsa in utdrag från servern.",
        "Kunde inte synkronisera med servern.",
    ),
    "af": (
        "Bewaar snippette in jou blaaier of meld aan om dit met jou rekening te sinkroniseer. Wissel tussen bekyk en wysig, kopieer met een klik, kies taal of outo-opsporing, en formatteer JSON, SQL of Monaco-ondersteunde kode.",
        "Kon nie snippette van die bediener laai nie.",
        "Kon nie met die bediener sinkroniseer nie.",
    ),
    "ca": (
        "Emmagatzema fragments al navegador o inicia sessió per sincronitzar-los amb el teu compte. Canvia entre veure i editar, copia amb un clic, tria idioma o detecció automàtica i formata JSON, SQL o codi compatible amb Monaco.",
        "No s'han pogut carregar els fragments des del servidor.",
        "No s'ha pogut sincronitzar amb el servidor.",
    ),
}


def eu_fr(
    loc: str,
    *,
    title: str,
    snippets: str,
    new_sn: str,
    new_t: str,
    welcome: str,
    c1: str,
    c2: str,
    sph: str,
    sar: str,
    emp: str,
    st: str,
    stp: str,
    lng: str,
    det: str,
    bdg: str,
    vw: str,
    ed: str,
    cp: str,
    cpd: str,
    fm: str,
    cn: str,
    dt: str,
    dd: str,
    dok: str,
    ear: str,
    eld: str,
    t_cpd: str,
    t_cpf: str,
    t_ntc: str,
    t_fmt: str,
    t_ff: str,
    t_fj: str,
    t_fu: str,
    t_del: str,
) -> dict:
    s0, s1, s2 = SUB[loc]
    return pack(
        loc,
        title=title,
        snippets=snippets,
        new_snippet=new_sn,
        new_title=new_t,
        welcome=welcome,
        c1=c1,
        c2=c2,
        search_ph=sph,
        search_ar=sar,
        empty=emp,
        st=st,
        st_ph=stp,
        lang=lng,
        det=det,
        badge=bdg,
        view=vw,
        edit=ed,
        copy=cp,
        copied=cpd,
        fmt=fm,
        cancel=cn,
        del_t=dt,
        del_d=dd,
        del_ok=dok,
        ed_ar=ear,
        ed_ld=eld,
        tc=t_cpd,
        tcf=t_cpf,
        tnt=t_ntc,
        tfm=t_fmt,
        tff=t_ff,
        tfj=t_fj,
        tfu=t_fu,
        tdel=t_del,
        tlf=s1,
        tsf=s2,
        sub=s0,
    )


PATCHES: dict[str, dict] = {}

PATCHES["fr"] = eu_fr(
    "fr",
    title="Gestionnaire d'extraits de code",
    snippets="Extraits",
    new_sn="Nouvel extrait",
    new_t="Nouvel extrait",
    welcome="Bienvenue",
    c1="// Bienvenue dans Extraits de code",
    c2="// Essayez Affichage / Édition, Copier, Formater et langage auto",
    sph="Rechercher des extraits…",
    sar="Rechercher des extraits",
    emp="Aucun extrait ne correspond à votre recherche.",
    st="Titre",
    stp="Nom de l'extrait",
    lng="Langage",
    det="Coloration syntaxique : {lang}",
    bdg="Auto · {lang}",
    vw="Lecture",
    ed="Édition",
    cp="Copier",
    cpd="Copié",
    fm="Formater",
    cn="Annuler",
    dt="Supprimer l'extrait ?",
    dd="« {title} » sera supprimé de ce navigateur.",
    dok="Supprimer",
    ear="Éditeur de code de l'extrait",
    eld="Chargement de l'éditeur…",
    t_cpd="Copié dans le presse-papiers",
    t_cpf="Impossible de copier",
    t_ntc="Rien à copier",
    t_fmt="Formaté",
    t_ff="Impossible de formater",
    t_fj="JSON invalide — corrigez la syntaxe d'abord",
    t_fu="Pas de formateur pour ce langage — essayez JSON ou SQL, ou passez en mode édition",
    t_del="Extrait supprimé",
)

PATCHES["de"] = eu_fr(
    "de",
    title="Code-Snippet-Manager",
    snippets="Snippets",
    new_sn="Neues Snippet",
    new_t="Neues Snippet",
    welcome="Willkommen",
    c1="// Willkommen bei Code-Snippets",
    c2="// Testen Sie Ansicht vs. Bearbeiten, Kopieren, Formatieren und Auto-Sprache",
    sph="Snippets durchsuchen…",
    sar="Snippets durchsuchen",
    emp="Keine Snippets entsprechen Ihrer Suche.",
    st="Titel",
    stp="Snippet-Name",
    lng="Sprache",
    det="Hervorhebung als {lang}",
    bdg="Auto · {lang}",
    vw="Ansicht",
    ed="Bearbeiten",
    cp="Kopieren",
    cpd="Kopiert",
    fm="Formatieren",
    cn="Abbrechen",
    dt="Snippet löschen?",
    dd="„{title}“ wird aus diesem Browser entfernt.",
    dok="Löschen",
    ear="Snippet-Code-Editor",
    eld="Editor wird geladen…",
    t_cpd="In die Zwischenablage kopiert",
    t_cpf="Kopieren fehlgeschlagen",
    t_ntc="Nichts zu kopieren",
    t_fmt="Formatiert",
    t_ff="Formatierung fehlgeschlagen",
    t_fj="Ungültiges JSON — zuerst Syntax beheben",
    t_fu="Kein Formatierer für diese Sprache — JSON oder SQL versuchen oder Bearbeiten",
    t_del="Snippet gelöscht",
)

PATCHES["es"] = eu_fr(
    "es",
    title="Administrador de fragmentos de código",
    snippets="Fragmentos",
    new_sn="Nuevo fragmento",
    new_t="Nuevo fragmento",
    welcome="Bienvenido",
    c1="// Bienvenido a Fragmentos de código",
    c2="// Prueba Ver vs Editar, Copiar, Formatear y idioma automático",
    sph="Buscar fragmentos…",
    sar="Buscar fragmentos",
    emp="Ningún fragmento coincide con tu búsqueda.",
    st="Título",
    stp="Nombre del fragmento",
    lng="Lenguaje",
    det="Resaltado como {lang}",
    bdg="Auto · {lang}",
    vw="Ver",
    ed="Editar",
    cp="Copiar",
    cpd="Copiado",
    fm="Formatear",
    cn="Cancelar",
    dt="¿Eliminar fragmento?",
    dd="«{title}» se eliminará de este navegador.",
    dok="Eliminar",
    ear="Editor de código del fragmento",
    eld="Cargando editor…",
    t_cpd="Copiado al portapapeles",
    t_cpf="No se pudo copiar",
    t_ntc="Nada que copiar",
    t_fmt="Formateado",
    t_ff="No se pudo formatear",
    t_fj="JSON no válido — corrige la sintaxis primero",
    t_fu="Sin formateador para este lenguaje — prueba JSON o SQL, o modo edición",
    t_del="Fragmento eliminado",
)

PATCHES["it"] = eu_fr(
    "it",
    title="Gestore snippet di codice",
    snippets="Snippet",
    new_sn="Nuovo snippet",
    new_t="Nuovo snippet",
    welcome="Benvenuto",
    c1="// Benvenuto negli snippet di codice",
    c2="// Prova Visualizza vs Modifica, Copia, Formatta e lingua automatica",
    sph="Cerca snippet…",
    sar="Cerca snippet",
    emp="Nessuno snippet corrisponde alla ricerca.",
    st="Titolo",
    stp="Nome snippet",
    lng="Linguaggio",
    det="Evidenziazione come {lang}",
    bdg="Auto · {lang}",
    vw="Visualizza",
    ed="Modifica",
    cp="Copia",
    cpd="Copiato",
    fm="Formatta",
    cn="Annulla",
    dt="Eliminare lo snippet?",
    dd="«{title}» verrà rimosso da questo browser.",
    dok="Elimina",
    ear="Editor codice snippet",
    eld="Caricamento editor…",
    t_cpd="Copiato negli appunti",
    t_cpf="Impossibile copiare",
    t_ntc="Niente da copiare",
    t_fmt="Formattato",
    t_ff="Impossibile formattare",
    t_fj="JSON non valido — correggi prima la sintassi",
    t_fu="Nessun formattatore per questo linguaggio — prova JSON o SQL o la modalità modifica",
    t_del="Snippet eliminato",
)

PATCHES["nl"] = eu_fr(
    "nl",
    title="Codefragmentbeheer",
    snippets="Fragmenten",
    new_sn="Nieuw fragment",
    new_t="Nieuw fragment",
    welcome="Welkom",
    c1="// Welkom bij codefragmenten",
    c2="// Probeer bekijken vs bewerken, kopiëren, formatteren en automatische taal",
    sph="Fragmenten zoeken…",
    sar="Fragmenten zoeken",
    emp="Geen fragmenten komen overeen met je zoekopdracht.",
    st="Titel",
    stp="Fragmentnaam",
    lng="Taal",
    det="Markering als {lang}",
    bdg="Auto · {lang}",
    vw="Bekijken",
    ed="Bewerken",
    cp="Kopiëren",
    cpd="Gekopieerd",
    fm="Formatteren",
    cn="Annuleren",
    dt="Fragment verwijderen?",
    dd="‘{title}’ wordt uit deze browser verwijderd.",
    dok="Verwijderen",
    ear="Fragmentcode-editor",
    eld="Editor laden…",
    t_cpd="Gekopieerd naar klembord",
    t_cpf="Kopiëren mislukt",
    t_ntc="Niets om te kopiëren",
    t_fmt="Geformatteerd",
    t_ff="Formatteren mislukt",
    t_fj="Ongeldige JSON — los eerst de syntaxis op",
    t_fu="Geen formatter voor deze taal — probeer JSON of SQL, of bewerkingsmodus",
    t_del="Fragment verwijderd",
)

PATCHES["pl"] = eu_fr(
    "pl",
    title="Menedżer fragmentów kodu",
    snippets="Fragmenty",
    new_sn="Nowy fragment",
    new_t="Nowy fragment",
    welcome="Witamy",
    c1="// Witamy we fragmentach kodu",
    c2="// Wypróbuj widok vs edycja, kopiowanie, formatowanie i auto-język",
    sph="Szukaj fragmentów…",
    sar="Szukaj fragmentów",
    emp="Brak fragmentów pasujących do wyszukiwania.",
    st="Tytuł",
    stp="Nazwa fragmentu",
    lng="Język",
    det="Podświetlanie: {lang}",
    bdg="Auto · {lang}",
    vw="Podgląd",
    ed="Edycja",
    cp="Kopiuj",
    cpd="Skopiowano",
    fm="Formatuj",
    cn="Anuluj",
    dt="Usunąć fragment?",
    dd="„{title}” zostanie usunięty z tej przeglądarki.",
    dok="Usuń",
    ear="Edytor kodu fragmentu",
    eld="Ładowanie edytora…",
    t_cpd="Skopiowano do schowka",
    t_cpf="Nie udało się skopiować",
    t_ntc="Nic do skopiowania",
    t_fmt="Sformatowano",
    t_ff="Nie udało się sformatować",
    t_fj="Nieprawidłowy JSON — najpierw popraw składnię",
    t_fu="Brak formatu dla tego języka — spróbuj JSON lub SQL albo tryb edycji",
    t_del="Fragment usunięty",
)

PATCHES["pt"] = eu_fr(
    "pt",
    title="Gestor de excertos de código",
    snippets="Excertos",
    new_sn="Novo excerto",
    new_t="Novo excerto",
    welcome="Bem-vindo",
    c1="// Bem-vindo aos excertos de código",
    c2="// Experimente Ver vs Editar, Copiar, Formatar e idioma automático",
    sph="Pesquisar excertos…",
    sar="Pesquisar excertos",
    emp="Nenhum excerto corresponde à pesquisa.",
    st="Título",
    stp="Nome do excerto",
    lng="Linguagem",
    det="Realce como {lang}",
    bdg="Auto · {lang}",
    vw="Ver",
    ed="Editar",
    cp="Copiar",
    cpd="Copiado",
    fm="Formatar",
    cn="Cancelar",
    dt="Eliminar excerto?",
    dd="«{title}» será removido deste navegador.",
    dok="Eliminar",
    ear="Editor de código do excerto",
    eld="A carregar editor…",
    t_cpd="Copiado para a área de transferência",
    t_cpf="Não foi possível copiar",
    t_ntc="Nada para copiar",
    t_fmt="Formatado",
    t_ff="Não foi possível formatar",
    t_fj="JSON inválido — corrija a sintaxe primeiro",
    t_fu="Sem formatador para esta linguagem — tente JSON ou SQL, ou modo de edição",
    t_del="Excerto eliminado",
)

PATCHES["pt-BR"] = eu_fr(
    "pt-BR",
    title="Gerenciador de trechos de código",
    snippets="Trechos",
    new_sn="Novo trecho",
    new_t="Novo trecho",
    welcome="Bem-vindo",
    c1="// Bem-vindo aos trechos de código",
    c2="// Experimente Ver vs Editar, Copiar, Formatar e idioma automático",
    sph="Buscar trechos…",
    sar="Buscar trechos",
    emp="Nenhum trecho corresponde à busca.",
    st="Título",
    stp="Nome do trecho",
    lng="Linguagem",
    det="Realce como {lang}",
    bdg="Auto · {lang}",
    vw="Ver",
    ed="Editar",
    cp="Copiar",
    cpd="Copiado",
    fm="Formatar",
    cn="Cancelar",
    dt="Excluir trecho?",
    dd="“{title}” será removido deste navegador.",
    dok="Excluir",
    ear="Editor de código do trecho",
    eld="Carregando editor…",
    t_cpd="Copiado para a área de transferência",
    t_cpf="Não foi possível copiar",
    t_ntc="Nada para copiar",
    t_fmt="Formatado",
    t_ff="Não foi possível formatar",
    t_fj="JSON inválido — corrija a sintaxe primeiro",
    t_fu="Sem formatador para esta linguagem — tente JSON ou SQL, ou modo de edição",
    t_del="Trecho excluído",
)

PATCHES["ru"] = eu_fr(
    "ru",
    title="Менеджер фрагментов кода",
    snippets="Сниппеты",
    new_sn="Новый сниппет",
    new_t="Новый сниппет",
    welcome="Добро пожаловать",
    c1="// Добро пожаловать в фрагменты кода",
    c2="// Попробуйте просмотр и правку, копирование, форматирование и автоязык",
    sph="Поиск сниппетов…",
    sar="Поиск сниппетов",
    emp="Нет сниппетов по запросу.",
    st="Заголовок",
    stp="Имя сниппета",
    lng="Язык",
    det="Подсветка: {lang}",
    bdg="Авто · {lang}",
    vw="Просмотр",
    ed="Правка",
    cp="Копировать",
    cpd="Скопировано",
    fm="Форматировать",
    cn="Отмена",
    dt="Удалить сниппет?",
    dd="«{title}» будет удалён из этого браузера.",
    dok="Удалить",
    ear="Редактор кода сниппета",
    eld="Загрузка редактора…",
    t_cpd="Скопировано в буфер",
    t_cpf="Не удалось скопировать",
    t_ntc="Нечего копировать",
    t_fmt="Отформатировано",
    t_ff="Не удалось отформатировать",
    t_fj="Неверный JSON — сначала исправьте синтаксис",
    t_fu="Нет форматтера для этого языка — попробуйте JSON или SQL или режим правки",
    t_del="Сниппет удалён",
)

PATCHES["uk"] = eu_fr(
    "uk",
    title="Менеджер фрагментів коду",
    snippets="Фрагменти",
    new_sn="Новий фрагмент",
    new_t="Новий фрагмент",
    welcome="Ласкаво просимо",
    c1="// Ласкаво просимо до фрагментів коду",
    c2="// Спробуйте перегляд і редагування, копіювання, форматування та авто-мову",
    sph="Пошук фрагментів…",
    sar="Пошук фрагментів",
    emp="Немає фрагментів за запитом.",
    st="Заголовок",
    stp="Назва фрагмента",
    lng="Мова",
    det="Підсвічування: {lang}",
    bdg="Авто · {lang}",
    vw="Перегляд",
    ed="Редагування",
    cp="Копіювати",
    cpd="Скопійовано",
    fm="Форматувати",
    cn="Скасувати",
    dt="Видалити фрагмент?",
    dd="«{title}» буде вилучено з цього браузера.",
    dok="Видалити",
    ear="Редактор коду фрагмента",
    eld="Завантаження редактора…",
    t_cpd="Скопійовано в буфер",
    t_cpf="Не вдалося скопіювати",
    t_ntc="Нічого копіювати",
    t_fmt="Відформатовано",
    t_ff="Не вдалося відформатувати",
    t_fj="Некоректний JSON — спочатку виправте синтаксис",
    t_fu="Немає форматера для цієї мови — спробуйте JSON або SQL або режим редагування",
    t_del="Фрагмент видалено",
)

PATCHES["tr"] = eu_fr(
    "tr",
    title="Kod parçacığı yöneticisi",
    snippets="Parçacıklar",
    new_sn="Yeni parçacık",
    new_t="Yeni parçacık",
    welcome="Hoş geldiniz",
    c1="// Kod parçacıklarına hoş geldiniz",
    c2="// Görüntüle vs düzenle, kopyala, biçimlendir ve otomatik dil deneyin",
    sph="Parçacık ara…",
    sar="Parçacık ara",
    emp="Aramanızla eşleşen parçacık yok.",
    st="Başlık",
    stp="Parçacık adı",
    lng="Dil",
    det="Vurgulama: {lang}",
    bdg="Otomatik · {lang}",
    vw="Görüntüle",
    ed="Düzenle",
    cp="Kopyala",
    cpd="Kopyalandı",
    fm="Biçimlendir",
    cn="İptal",
    dt="Parçacık silinsin mi?",
    dd="“{title}” bu tarayıcıdan kaldırılacak.",
    dok="Sil",
    ear="Parçacık kod düzenleyici",
    eld="Düzenleyici yükleniyor…",
    t_cpd="Panoya kopyalandı",
    t_cpf="Kopyalanamadı",
    t_ntc="Kopyalanacak bir şey yok",
    t_fmt="Biçimlendirildi",
    t_ff="Biçimlendirilemedi",
    t_fj="Geçersiz JSON — önce sözdizimini düzeltin",
    t_fu="Bu dil için biçimlendirici yok — JSON veya SQL deneyin ya da düzenleme modunu kullanın",
    t_del="Parçacık silindi",
)

PATCHES["cs"] = eu_fr(
    "cs",
    title="Správce úryvků kódu",
    snippets="Úryvky",
    new_sn="Nový úryvek",
    new_t="Nový úryvek",
    welcome="Vítejte",
    c1="// Vítejte u úryvků kódu",
    c2="// Zkuste zobrazení vs úpravy, kopírování, formátování a automatický jazyk",
    sph="Hledat úryvky…",
    sar="Hledat úryvky",
    emp="Žádný úryvek neodpovídá hledání.",
    st="Název",
    stp="Název úryvku",
    lng="Jazyk",
    det="Zvýraznění: {lang}",
    bdg="Auto · {lang}",
    vw="Zobrazit",
    ed="Upravit",
    cp="Kopírovat",
    cpd="Zkopírováno",
    fm="Formátovat",
    cn="Zrušit",
    dt="Smazat úryvek?",
    dd="„{title}“ bude odebrán z tohoto prohlížeče.",
    dok="Smazat",
    ear="Editor kódu úryvku",
    eld="Načítání editoru…",
    t_cpd="Zkopírováno do schránky",
    t_cpf="Kopírování se nezdařilo",
    t_ntc="Nic ke kopírování",
    t_fmt="Naformátováno",
    t_ff="Formátování se nezdařilo",
    t_fj="Neplatné JSON — nejdřív opravte syntaxi",
    t_fu="Pro tento jazyk není formátovač — zkuste JSON nebo SQL nebo režim úprav",
    t_del="Úryvek smazán",
)

PATCHES["el"] = eu_fr(
    "el",
    title="Διαχειριστής αποσπασμάτων κώδικα",
    snippets="Αποσπάσματα",
    new_sn="Νέο απόσπασμα",
    new_t="Νέο απόσπασμα",
    welcome="Καλώς ήρθατε",
    c1="// Καλώς ήρθατε στα αποσπάσματα κώδικα",
    c2="// Δοκιμάστε προβολή vs επεξεργασία, αντιγραφή, μορφοποίηση και αυτόματη γλώσσα",
    sph="Αναζήτηση αποσπασμάτων…",
    sar="Αναζήτηση αποσπασμάτων",
    emp="Κανένα απόσπασμα δεν ταιριάζει στην αναζήτηση.",
    st="Τίτλος",
    stp="Όνομα αποσπάσματος",
    lng="Γλώσσα",
    det="Τονισμός ως {lang}",
    bdg="Αυτόματο · {lang}",
    vw="Προβολή",
    ed="Επεξεργασία",
    cp="Αντιγραφή",
    cpd="Αντιγράφηκε",
    fm="Μορφοποίηση",
    cn="Άκυρο",
    dt="Διαγραφή αποσπάσματος;",
    dd="Το «{title}» θα αφαιρεθεί από αυτόν τον browser.",
    dok="Διαγραφή",
    ear="Επεξεργαστής κώδικα αποσπάσματος",
    eld="Φόρτωση επεξεργαστή…",
    t_cpd="Αντιγράφηκε στο πρόχειρο",
    t_cpf="Αδυναμία αντιγραφής",
    t_ntc="Τίποτα για αντιγραφή",
    t_fmt="Μορφοποιήθηκε",
    t_ff="Αδυναμία μορφοποίησης",
    t_fj="Μη έγκυρο JSON — διορθώστε πρώτα τη σύνταξη",
    t_fu="Δεν υπάρχει μορφοποιητής για αυτή τη γλώσσα — δοκιμάστε JSON ή SQL ή λειτουργία επεξεργασίας",
    t_del="Το απόσπασμα διαγράφηκε",
)

PATCHES["da"] = eu_fr(
    "da",
    title="Kodestykke-manager",
    snippets="Snippets",
    new_sn="Nyt snippet",
    new_t="Nyt snippet",
    welcome="Velkommen",
    c1="// Velkommen til kodestykker",
    c2="// Prøv visning vs redigering, kopiér, formatér og automatisk sprog",
    sph="Søg i snippets…",
    sar="Søg i snippets",
    emp="Ingen snippets matcher din søgning.",
    st="Titel",
    stp="Snippet-navn",
    lng="Sprog",
    det="Fremhævning som {lang}",
    bdg="Auto · {lang}",
    vw="Vis",
    ed="Rediger",
    cp="Kopiér",
    cpd="Kopieret",
    fm="Formatér",
    cn="Annuller",
    dt="Slet snippet?",
    dd="«{title}» fjernes fra denne browser.",
    dok="Slet",
    ear="Snippet-kodeeditor",
    eld="Indlæser editor…",
    t_cpd="Kopieret til udklipsholder",
    t_cpf="Kunne ikke kopiere",
    t_ntc="Intet at kopiere",
    t_fmt="Formateret",
    t_ff="Kunne ikke formatere",
    t_fj="Ugyldig JSON — ret syntaksen først",
    t_fu="Ingen formatter til dette sprog — prøv JSON eller SQL eller redigeringstilstand",
    t_del="Snippet slettet",
)

PATCHES["nb"] = eu_fr(
    "nb",
    title="Kodeutklipp-administrator",
    snippets="Utdrag",
    new_sn="Nytt utdrag",
    new_t="Nytt utdrag",
    welcome="Velkommen",
    c1="// Velkommen til kodeutdrag",
    c2="// Prøv visning vs redigering, kopier, formater og automatisk språk",
    sph="Søk i utdrag…",
    sar="Søk i utdrag",
    emp="Ingen utdrag samsvarer med søket.",
    st="Tittel",
    stp="Navn på utdrag",
    lng="Språk",
    det="Utheving som {lang}",
    bdg="Auto · {lang}",
    vw="Vis",
    ed="Rediger",
    cp="Kopier",
    cpd="Kopiert",
    fm="Formater",
    cn="Avbryt",
    dt="Slette utdrag?",
    dd="«{title}» fjernes fra denne nettleseren.",
    dok="Slett",
    ear="Kodeeditor for utdrag",
    eld="Laster editor…",
    t_cpd="Kopiert til utklippstavle",
    t_cpf="Kunne ikke kopiere",
    t_ntc="Ingenting å kopiere",
    t_fmt="Formatert",
    t_ff="Kunne ikke formatere",
    t_fj="Ugyldig JSON — rett syntaksen først",
    t_fu="Ingen formattering for dette språket — prøv JSON eller SQL eller redigeringsmodus",
    t_del="Utdrag slettet",
)

PATCHES["sv"] = eu_fr(
    "sv",
    title="Hanterare för kodutdrag",
    snippets="Utdrag",
    new_sn="Nytt utdrag",
    new_t="Nytt utdrag",
    welcome="Välkommen",
    c1="// Välkommen till kodutdrag",
    c2="// Prova visning vs redigera, kopiera, formatera och automatiskt språk",
    sph="Sök utdrag…",
    sar="Sök utdrag",
    emp="Inga utdrag matchar sökningen.",
    st="Titel",
    stp="Utdragsnamn",
    lng="Språk",
    det="Syntaxmarkering som {lang}",
    bdg="Auto · {lang}",
    vw="Visa",
    ed="Redigera",
    cp="Kopiera",
    cpd="Kopierat",
    fm="Formatera",
    cn="Avbryt",
    dt="Ta bort utdrag?",
    dd="”{title}” tas bort från den här webbläsaren.",
    dok="Ta bort",
    ear="Kodredigerare för utdrag",
    eld="Laddar redigerare…",
    t_cpd="Kopierat till urklipp",
    t_cpf="Kunde inte kopiera",
    t_ntc="Inget att kopiera",
    t_fmt="Formaterat",
    t_ff="Kunde inte formatera",
    t_fj="Ogiltig JSON — åtgärda syntaxen först",
    t_fu="Ingen formaterare för detta språk — prova JSON eller SQL eller redigeringsläge",
    t_del="Utdrag borttaget",
)

PATCHES["af"] = eu_fr(
    "af",
    title="Kodesnippet-bestuurder",
    snippets="Snippette",
    new_sn="Nuwe snippet",
    new_t="Nuwe snippet",
    welcome="Welkom",
    c1="// Welkom by kodesnippette",
    c2="// Probeer bekyk vs wysig, kopieer, formateer en outo-taal",
    sph="Soek snippette…",
    sar="Soek snippette",
    emp="Geen snippette pas by jou soektog nie.",
    st="Titel",
    stp="Snippett-naam",
    lng="Taal",
    det="Beklemtoning as {lang}",
    bdg="Outo · {lang}",
    vw="Bekyk",
    ed="Wysig",
    cp="Kopieer",
    cpd="Gekopieer",
    fm="Formateer",
    cn="Kanselleer",
    dt="Snippett uitvee?",
    dd="“{title}” sal uit hierdie blaaier verwyder word.",
    dok="Vee uit",
    ear="Snippett-kode-redigeerder",
    eld="Laai redigeerder…",
    t_cpd="Gekopieer na knipbord",
    t_cpf="Kon nie kopieer nie",
    t_ntc="Niks om te kopieer nie",
    t_fmt="Geformatteer",
    t_ff="Kon nie formateer nie",
    t_fj="Ongeldige JSON — herstel eers sintaksis",
    t_fu="Geen formateerder vir hierdie taal nie — probeer JSON of SQL of wysig-modus",
    t_del="Snippett uitgevee",
)

PATCHES["ca"] = eu_fr(
    "ca",
    title="Gestor de fragments de codi",
    snippets="Fragments",
    new_sn="Fragment nou",
    new_t="Fragment nou",
    welcome="Benvingut",
    c1="// Benvingut als fragments de codi",
    c2="// Prova veure vs editar, copia, formata i idioma automàtic",
    sph="Cerca fragments…",
    sar="Cerca fragments",
    emp="Cap fragment no coincideix amb la cerca.",
    st="Títol",
    stp="Nom del fragment",
    lng="Llenguatge",
    det="Ressaltat com a {lang}",
    bdg="Auto · {lang}",
    vw="Veure",
    ed="Editar",
    cp="Copiar",
    cpd="Copiat",
    fm="Formatejar",
    cn="Cancel·la",
    dt="Eliminar el fragment?",
    dd="«{title}» se suprimirà d'aquest navegador.",
    dok="Eliminar",
    ear="Editor de codi del fragment",
    eld="Carregant l'editor…",
    t_cpd="Copiat al porta-retalls",
    t_cpf="No s'ha pogut copiar",
    t_ntc="Res a copiar",
    t_fmt="Formatejat",
    t_ff="No s'ha pogut formatejar",
    t_fj="JSON no vàlid — corregeix la sintaxi primer",
    t_fu="Sense formatador per a aquest llenguatge — prova JSON o SQL o mode edició",
    t_del="Fragment eliminat",
)

# Arabic, Persian, CJK, Vietnamese, Indonesian, Malay — same eu_fr pattern with loc
PATCHES["ar"] = eu_fr(
    "ar",
    title="مدير مقاطع الشيفرة",
    snippets="المقاطع",
    new_sn="مقطع جديد",
    new_t="مقطع جديد",
    welcome="مرحبًا",
    c1="// مرحبًا بك في مقاطع الشيفرة",
    c2="// جرّب العرض مقابل التحرير، النسخ، التنسيق واللغة التلقائية",
    sph="البحث في المقاطع…",
    sar="البحث في المقاطع",
    emp="لا توجد مقاطع تطابق بحثك.",
    st="العنوان",
    stp="اسم المقطع",
    lng="اللغة",
    det="تمييز بناء الجملة: {lang}",
    bdg="تلقائي · {lang}",
    vw="عرض",
    ed="تحرير",
    cp="نسخ",
    cpd="تم النسخ",
    fm="تنسيق",
    cn="إلغاء",
    dt="حذف المقطع؟",
    dd="سيتم إزالة «{title}» من هذا المتصفح.",
    dok="حذف",
    ear="محرر شيفرة المقطع",
    eld="جاري تحميل المحرر…",
    t_cpd="تم النسخ إلى الحافظة",
    t_cpf="تعذّر النسخ",
    t_ntc="لا يوجد شيء للنسخ",
    t_fmt="تم التنسيق",
    t_ff="تعذّر التنسيق",
    t_fj="JSON غير صالح — صحّح الصياغة أولًا",
    t_fu="لا يوجد مُنسّق لهذه اللغة — جرّب JSON أو SQL أو وضع التحرير",
    t_del="تم حذف المقطع",
)

PATCHES["fa"] = eu_fr(
    "fa",
    title="مدیریت قطعه‌کد",
    snippets="قطعه‌کدها",
    new_sn="قطعه‌کد جدید",
    new_t="قطعه‌کد جدید",
    welcome="خوش آمدید",
    c1="// به قطعه‌کدها خوش آمدید",
    c2="// حالت مشاهده در برابر ویرایش، رونوشت، قالب‌بندی و زبان خودکار را امتحان کنید",
    sph="جستجوی قطعه‌کدها…",
    sar="جستجوی قطعه‌کدها",
    emp="هیچ قطعه‌ای با جستجو هم‌خوان نیست.",
    st="عنوان",
    stp="نام قطعه",
    lng="زبان",
    det="برجسته‌سازی به‌صورت {lang}",
    bdg="خودکار · {lang}",
    vw="مشاهده",
    ed="ویرایش",
    cp="رونوشت",
    cpd="رونوشت شد",
    fm="قالب‌بندی",
    cn="لغو",
    dt="قطعه‌کد حذف شود؟",
    dd="«{title}» از این مرورگر حذف می‌شود.",
    dok="حذف",
    ear="ویرایشگر کد قطعه",
    eld="در حال بارگذاری ویرایشگر…",
    t_cpd="در بریده‌دان رونوشت شد",
    t_cpf="رونوشت ممکن نشد",
    t_ntc="چیزی برای رونوشت نیست",
    t_fmt="قالب‌بندی شد",
    t_ff="قالب‌بندی ممکن نشد",
    t_fj="JSON نامعتبر — نخست نحو را درست کنید",
    t_fu="قالب‌بند برای این زبان نیست — JSON یا SQL یا حالت ویرایش را امتحان کنید",
    t_del="قطعه حذف شد",
)

PATCHES["zh"] = eu_fr(
    "zh",
    title="代码片段管理器",
    snippets="片段",
    new_sn="新建片段",
    new_t="新建片段",
    welcome="欢迎",
    c1="// 欢迎使用代码片段",
    c2="// 试试查看/编辑、复制、格式化与自动语言",
    sph="搜索片段…",
    sar="搜索片段",
    emp="没有匹配的片段。",
    st="标题",
    stp="片段名称",
    lng="语言",
    det="高亮为 {lang}",
    bdg="自动 · {lang}",
    vw="查看",
    ed="编辑",
    cp="复制",
    cpd="已复制",
    fm="格式化",
    cn="取消",
    dt="删除片段？",
    dd="将从此浏览器移除「{title}」。",
    dok="删除",
    ear="片段代码编辑器",
    eld="正在加载编辑器…",
    t_cpd="已复制到剪贴板",
    t_cpf="无法复制",
    t_ntc="没有可复制的内容",
    t_fmt="已格式化",
    t_ff="无法格式化",
    t_fj="JSON 无效 — 请先修正语法",
    t_fu="此语言没有格式化程序 — 请尝试 JSON 或 SQL，或使用编辑模式",
    t_del="片段已删除",
)

PATCHES["ja"] = eu_fr(
    "ja",
    title="コードスニペットマネージャー",
    snippets="スニペット",
    new_sn="新しいスニペット",
    new_t="新しいスニペット",
    welcome="ようこそ",
    c1="// コードスニペットへようこそ",
    c2="// 表示と編集、コピー、整形、自動言語をお試しください",
    sph="スニペットを検索…",
    sar="スニペットを検索",
    emp="一致するスニペットがありません。",
    st="タイトル",
    stp="スニペット名",
    lng="言語",
    det="ハイライト: {lang}",
    bdg="自動 · {lang}",
    vw="表示",
    ed="編集",
    cp="コピー",
    cpd="コピーしました",
    fm="整形",
    cn="キャンセル",
    dt="スニペットを削除しますか？",
    dd="「{title}」はこのブラウザから削除されます。",
    dok="削除",
    ear="スニペットコードエディター",
    eld="エディターを読み込み中…",
    t_cpd="クリップボードにコピーしました",
    t_cpf="コピーできませんでした",
    t_ntc="コピーする内容がありません",
    t_fmt="整形しました",
    t_ff="整形できませんでした",
    t_fj="無効な JSON — 先に構文を修正してください",
    t_fu="この言語用の整形はありません — JSON か SQL、または編集モードをお試しください",
    t_del="スニペットを削除しました",
)

PATCHES["ko"] = eu_fr(
    "ko",
    title="코드 스니펫 관리자",
    snippets="스니펫",
    new_sn="새 스니펫",
    new_t="새 스니펫",
    welcome="환영합니다",
    c1="// 코드 스니펫에 오신 것을 환영합니다",
    c2="// 보기/편집, 복사, 서식 및 자동 언어를 사용해 보세요",
    sph="스니펫 검색…",
    sar="스니펫 검색",
    emp="검색과 일치하는 스니펫이 없습니다.",
    st="제목",
    stp="스니펫 이름",
    lng="언어",
    det="강조: {lang}",
    bdg="자동 · {lang}",
    vw="보기",
    ed="편집",
    cp="복사",
    cpd="복사됨",
    fm="서식",
    cn="취소",
    dt="스니펫을 삭제할까요?",
    dd="‘{title}’이(가) 이 브라우저에서 제거됩니다.",
    dok="삭제",
    ear="스니펫 코드 편집기",
    eld="편집기 로드 중…",
    t_cpd="클립보드에 복사됨",
    t_cpf="복사할 수 없습니다",
    t_ntc="복사할 내용이 없습니다",
    t_fmt="서식이 적용되었습니다",
    t_ff="서식을 적용할 수 없습니다",
    t_fj="잘못된 JSON — 먼저 구문을 수정하세요",
    t_fu="이 언어용 서식 도구가 없습니다 — JSON 또는 SQL 또는 편집 모드를 사용해 보세요",
    t_del="스니펫이 삭제되었습니다",
)

PATCHES["vi"] = eu_fr(
    "vi",
    title="Trình quản lý đoạn mã",
    snippets="Đoạn mã",
    new_sn="Đoạn mới",
    new_t="Đoạn mới",
    welcome="Chào mừng",
    c1="// Chào mừng đến với đoạn mã",
    c2="// Thử xem so với sửa, sao chép, định dạng và ngôn ngữ tự động",
    sph="Tìm đoạn mã…",
    sar="Tìm đoạn mã",
    emp="Không có đoạn mã khớp tìm kiếm.",
    st="Tiêu đề",
    stp="Tên đoạn",
    lng="Ngôn ngữ",
    det="Tô sáng dạng {lang}",
    bdg="Tự động · {lang}",
    vw="Xem",
    ed="Sửa",
    cp="Sao chép",
    cpd="Đã sao chép",
    fm="Định dạng",
    cn="Hủy",
    dt="Xóa đoạn mã?",
    dd="“{title}” sẽ bị xóa khỏi trình duyệt này.",
    dok="Xóa",
    ear="Trình sửa mã đoạn",
    eld="Đang tải trình sửa…",
    t_cpd="Đã sao chép vào bảng tạm",
    t_cpf="Không thể sao chép",
    t_ntc="Không có gì để sao chép",
    t_fmt="Đã định dạng",
    t_ff="Không thể định dạng",
    t_fj="JSON không hợp lệ — sửa cú pháp trước",
    t_fu="Không có bộ định dạng cho ngôn ngữ này — thử JSON hoặc SQL hoặc chế độ sửa",
    t_del="Đã xóa đoạn mã",
)

PATCHES["id"] = eu_fr(
    "id",
    title="Pengelola cuplikan kode",
    snippets="Cuplikan",
    new_sn="Cuplikan baru",
    new_t="Cuplikan baru",
    welcome="Selamat datang",
    c1="// Selamat datang di cuplikan kode",
    c2="// Coba lihat vs sunting, salin, format, dan bahasa otomatis",
    sph="Cari cuplikan…",
    sar="Cari cuplikan",
    emp="Tidak ada cuplikan yang cocok.",
    st="Judul",
    stp="Nama cuplikan",
    lng="Bahasa",
    det="Sorotan sebagai {lang}",
    bdg="Otomatis · {lang}",
    vw="Lihat",
    ed="Sunting",
    cp="Salin",
    cpd="Disalin",
    fm="Format",
    cn="Batal",
    dt="Hapus cuplikan?",
    dd="“{title}” akan dihapus dari browser ini.",
    dok="Hapus",
    ear="Editor kode cuplikan",
    eld="Memuat editor…",
    t_cpd="Disalin ke papan klip",
    t_cpf="Tidak dapat menyalin",
    t_ntc="Tidak ada yang disalin",
    t_fmt="Sudah diformat",
    t_ff="Tidak dapat memformat",
    t_fj="JSON tidak valid — perbaiki sintaks dulu",
    t_fu="Tidak ada pemformat untuk bahasa ini — coba JSON atau SQL atau mode sunting",
    t_del="Cuplikan dihapus",
)

PATCHES["ms"] = eu_fr(
    "ms",
    title="Pengurus petikan kod",
    snippets="Petikan",
    new_sn="Petikan baharu",
    new_t="Petikan baharu",
    welcome="Selamat datang",
    c1="// Selamat datang ke petikan kod",
    c2="// Cuba lihat vs sunting, salin, format dan bahasa automatik",
    sph="Cari petikan…",
    sar="Cari petikan",
    emp="Tiada petikan sepadan.",
    st="Tajuk",
    stp="Nama petikan",
    lng="Bahasa",
    det="Sorotan sebagai {lang}",
    bdg="Auto · {lang}",
    vw="Lihat",
    ed="Sunting",
    cp="Salin",
    cpd="Disalin",
    fm="Format",
    cn="Batal",
    dt="Padam petikan?",
    dd="“{title}” akan dibuang daripada pelayar ini.",
    dok="Padam",
    ear="Editor kod petikan",
    eld="Memuatkan editor…",
    t_cpd="Disalin ke papan keratan",
    t_cpf="Tidak dapat menyalin",
    t_ntc="Tiada untuk disalin",
    t_fmt="Telah diformat",
    t_ff="Tidak dapat memformat",
    t_fj="JSON tidak sah — betulkan sintaks dahulu",
    t_fu="Tiada pemformat untuk bahasa ini — cuba JSON atau SQL atau mod sunting",
    t_del="Petikan dipadam",
)


def main() -> None:
    OUT.write_text(
        json.dumps(PATCHES, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    OUT_NAV_DASH.write_text(
        json.dumps(NAV_DASH, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print("Wrote", OUT, "locales:", len(PATCHES))
    print("Wrote", OUT_NAV_DASH, "locales:", len(NAV_DASH))


if __name__ == "__main__":
    main()
